- name: Add nginx.repo
  template:
    src: nginx.repo
    dest: /etc/yum.repos.d/

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Copy nginx.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/
  notify:
    - Reload Nginx

- name: Start and enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Add firewalld rule for Nginx
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items:
    - http
    - https
