- name: copy nginx.repo
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/

- name: install nginx
  yum:
    name: nginx
    state: present

- name: copy nginx.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/
  notify:
    - reload nginx

- name: start and enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: add firewalld rule for nginx
  firewalld:
    service: "{{ item }}"
    state: disabled
    permanent: yes
    immediate: yes
  with_items:
    - http
    - https
