php_enablerepo: remi-php{{ php_version | replace(".", "") }}

php_packages:
  - php
  - php-fpm
  - php-gd
  - php-intl
  - php-mbstring
  - php-mysqlnd
  - php-opcache
  - php-pdo
  - php-xml
  - php-pecl-zip
