nginx_worker_rlimit_nofile: 51200
nginx_worker_connections: 51200

nginx_multi_accept: "off"
nginx_accept_mutex: "off"

nginx_log_level: crit
nginx_error_log: /var/log/nginx/error.log
nginx_access_log: /var/log/nginx/access.log

nginx_server_tokens: "off"
nginx_server_names_hash_bucket_size: 128

nginx_client_max_body_size: 50m
nginx_client_header_buffer_size: 32k
nginx_large_client_header_buffers: 4 32k

nginx_sendfile: "on"
nginx_sendfile_max_chunk: 512K

nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: 60

nginx_fastcgi_connect_timeout: 300
nginx_fastcgi_send_timeout: 300
nginx_fastcgi_read_timeout: 300
nginx_fastcgi_buffers: 4 64k
nginx_fastcgi_buffer_size: 64k
nginx_fastcgi_busy_buffers_size: 128k
nginx_fastcgi_temp_file_write_size: 256k

nginx_gzip_vary: "on"
nginx_gzip_buffers: 4 16k
nginx_gzip_min_length: 1k
nginx_gzip_comp_level: 2
nginx_gzip_http_version: 1.1
nginx_gzip_disable: MSIE [1-6]\.
nginx_gzip_proxied:
  - expired
  - no-cache
  - no-store
  - private
  - auth
nginx_gzip_types:
  - text/plain
  - text/css
  - text/csv
  - text/xml
  - text/javascript
  - application/javascript
  - application/x-javascript
  - application/xml
  - application/xml+rss
  - application/json

nginx_proxy_cache_path: ""
