nginx_user: nginx

nginx_worker_connections: 51200

nginx_server_tokens: "Off"

nginx_proxy_cache_path: ""

nginx_log_format: |-
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'

nginx_default_port: 80
nginx_default_root: /home/wwwroot/default
nginx_default_fastcgi_pass: unix:/var/run/php-fpm/php-fpm.sock
