nginx_user: nginx

nginx_worker_connections: 51200

nginx_server_tokens: "Off"

nginx_proxy_cache_path: ""

nginx_default_port: 80
nginx_default_root: "{{ ansible_env.PWD }}/default"
nginx_default_fastcgi_pass: unix:/var/run/php-fpm/php-fpm.sock
