- name: Ensure tool directories exist
  file:
    path: "{{ tool_dir }}"
    state: directory

- name: Replace nginx default.conf
  template:
    src: default.conf
    dest: /etc/nginx/conf.d/
  notify:
    - Reload nginx
  become: yes

- name: Copy PHP Tools
  copy:
    src: "{{ item }}"
    dest: "{{ tool_dir }}"
  with_items:
    - p.php
    - ocp.php
    - phpinfo.php

- include: phpmyadmin.yml

- include: phpredisadmin.yml
