- name: Ensure default directory exists
  file:
    path: "{{ default_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
  become: yes

- name: Copy index.html
  copy:
    src: index.html
    dest: "{{ default_dir }}"

- name: Replace nginx default.conf
  template:
    src: default.conf
    dest: /etc/nginx/conf.d/
  notify:
    - Reload nginx
  become: yes

- name: Ensure tool directory exists
  file:
    path: "{{ tool_dir }}"
    state: directory

- name: Copy PHP tools
  copy:
    src: "{{ item }}"
    dest: "{{ tool_dir }}"
  with_items:
    - p.php
    - ocp.php
    - phpinfo.php

- include: phpmyadmin.yml

- include: phpredisadmin.yml

- name: Change group of default directory
  file:
    path: "{{ default_dir }}"
    group: "{{ php_fpm_group }}"
    recurse: yes
