- name: Ensure tool directories exist
  file:
    path: "{{ tool_dir }}"
    state: directory
    mode: 0775
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes

- name: Replace nginx default.conf
  template:
    src: default.conf
    dest: /etc/nginx/conf.d/
  notify:
    - Reload nginx
  become: yes

- name: Copy index.html
  copy:
    src: index.html
    dest: "{{ default_dir }}"

- name: Copy PHP Tools
  copy:
    src: "{{ item }}"
    dest: "{{ tool_dir }}"
  with_items:
    - p.php
    - ocp.php
    - phpinfo.php

- include: phpmyadmin.yml

- include: phpredisadmin.yml
