- name: Check if phpMyAdmin is installed
  stat:
    path: "{{ phpmyadmin_path }}"
  register: phpmyadmin

- name: Install phpMyAdmin
  composer:
    command: create-project
    arguments: "{{ phpmyadmin_package }}"
    working_dir: "{{ tool_dir }}"
    prefer_dist: yes
  when: not phpmyadmin.stat.exists

- name: Create phpMyAdmin config file
  copy:
    src: "{{ phpmyadmin_path }}/config.sample.inc.php"
    dest: "{{ phpmyadmin_config_file }}"
    force: no
    remote_src: yes

- name: Modify phpMyAdmin configuration
  lineinfile:
    path: "{{ phpmyadmin_config_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "\\$cfg\\['blowfish_secret'\\]", line: "$cfg['blowfish_secret'] = '{{ phpmyadmin_blowfish_secret }}';"}
    - { regexp: "\\$cfg\\['LoginCookieValidity'\\]", line: "$cfg['LoginCookieValidity'] = {{ phpmyadmin_cookie_lifetime }};"}

- name: Change group of phpMyAdmin directory
  file:
    path: "{{ phpmyadmin_path }}"
    group: "{{ php_fpm_group }}"
    mode: g+w
