- name: Check if phpRedisAdmin is installed
  stat:
    path: "{{ phpredisadmin_path }}"
  register: phpredisadmin

- name: Install phpRedisAdmin
  composer:
    command: create-project
    arguments: "{{ phpredisadmin_package }}"
    working_dir: "{{ web_tool_dir }}"
    prefer_dist: yes
  when: not phpredisadmin.stat.exists
