- name: Copy mysql-community.repo
  template:
    src: mysql-community.repo
    dest: /etc/yum.repos.d/

- name: Install MySQL
  yum:
    name: mysql-community-server
    state: present

- name: Start and enable MySQL
  systemd:
    name: mysqld
    state: started
    enabled: yes
