- name: copy mysql-community.repo
  template:
    src: mysql-community.repo
    dest: /etc/yum.repos.d/

- name: install mysql
  yum:
    name: mysql-community-server
    enablerepo: mysql-community
    state: present

- name: start and enable mysql
  systemd:
    name: mysqld
    state: started
    enabled: yes
