- name: Add mysql-community.repo
  template:
    src: mysql-community.repo
    dest: /etc/yum.repos.d/

- name: Install MySQL and MySQL-python
  yum:
    name:
      - mysql-community-server
      - MySQL-python
    state: present

- name: Copy my.cnf
  template:
    src: my.cnf
    dest: /etc/
  notify:
    - Restart MySQL

- name: Start and enable MySQL
  systemd:
    name: mysqld
    state: started
    enabled: yes

- include: user.yml
