- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: add firewalld rule for nginx
  firewalld:
    service: "{{ item }}"
    state: disabled
    permanent: yes
    immediate: yes
  with_items:
    - http
    - https
