web_default_dir: "/var/www/default"
web_tool_dir: "{{ web_default_dir }}/tools"

phpmyadmin_path: "{{ web_tool_dir }}/phpmyadmin"
phpmyadmin_package: phpmyadmin/phpmyadmin

phpredisadmin_path: "{{ web_tool_dir }}/php-redis-admin"
phpredisadmin_package: erik-dubbelboer/php-redis-admin
