- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- name: Set timezone to {{ timezone }}
  timezone:
    name: "{{ timezone }}"

- name: Set nofile limits
  pam_limits:
    domain: "*"
    limit_type: "{{ item }}"
    limit_item: nofile
    value: "{{ limit }}"
  with_items:
    - soft
    - hard

- include: yum.yml

- include: firewalld.yml
