- name: set hostname if hostname is defined
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- name: change timezone to {{ timezone }}
  timezone:
    name: "{{ timezone }}"

- name: set nofile limits
  pam_limits:
    domain: "*"
    limit_type: "{{ item }}"
    limit_item: nofile
    value: "{{ limit }}"
  with_items:
    - soft
    - hard

- name: disable selinux
  selinux:
    state: disabled

- include: yum.yml

- include: firewalld.yml
