- name: Install remi.repo
  yum:
    name: "{{ remi_repo }}"
    state: present

- name: Install PHP {{ php_version }} packages
  yum:
    name: "{{ php_packages }}"
    enablerepo: remi-php{{ php_version | replace(".", "") }}
    state: present

# - name: copy php.ini and www.conf

- name: Start and enable PHP-FPM
  systemd:
    name: php-fpm
    state: started
    enabled: yes
