- name: Ensure Remi repo is installed
  yum:
    name: "{{ remi_repo }}"
    state: present

- name: Install PHP {{ php_version }} packages
  yum:
    name: "{{ php_packages + php_packages_extra }}"
    enablerepo: "{{ php_enablerepo }}"
    state: present

- name: Copy PHP and PHP-FPM config files
  template:
    src: "{{ item }}"
    dest: /etc/
  with_items:
    - php.ini
    - php-fpm.conf
  notify:
    - Reload PHP-FPM

- name: Start and enable PHP-FPM
  systemd:
    name: php-fpm
    state: started
    enabled: yes

- include: composer.yml
  when: php_composer_enabled
