- name: Install PHP {{ php_version }} packages
  yum:
    name: "{{ php_packages + php_packages_extra }}"
    enablerepo: "{{ php_enablerepo }}"
    state: present

- name: Copy php.ini and php-fpm.conf
  template:
    src: "{{ item }}"
    dest: /etc/
  notify:
    - Reload PHP-FPM
  with_items:
    - php.ini
    - php-fpm.conf

- name: Start and enable PHP-FPM
  systemd:
    name: php-fpm
    state: started
    enabled: yes

- include: composer.yml
  when: php_composer_enable
