- name: install remi.repo
  yum:
    name: "{{ remi_repo }}"
    state: present

- name: install php{{ php_version }} packages
  yum:
    name: "{{ php_packages }}"
    enablerepo: remi-php{{ php_version }}
    state: present

# - name: copy php.ini and www.conf

- name: start and enable php-fpm
  systemd:
    name: php-fpm
    state: started
    enabled: yes
