- name: Reload php-fpm
  systemd:
    name: php-fpm
    state: reloaded

- name: Change Composer repository
  composer:
    command: config
    arguments: -g repo.packagist composer {{ php_composer_repo }}
    working_dir: "{{ ansible_env.PWD }}"
  become: no
